/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zedar' at '23.09.15 08:03' with Gradle 2.7
 *
 * @author zedar, @date 23.09.15 08:03
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
